apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-jusan
spec:
  selector:
    matchLabels:
      app: db-jusan
  serviceName: db-jusan
  replicas: 1
  template:
    metadata:
      labels:
        app: db-jusan
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: www
          mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name: db-jusan
spec:
  selector:
    app: db-jusan
  ports:
  - port: 1221
    targetPort: 5432


